[package]
name = "no_packsaran"
version = "0.0.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
combination = "0.2.2"
palette = { version = "0.7.6", default-features = false, features = ["std"] }
plumers = "1.0.2"
xflags = "0.3.2"
